export default {
  mymap: require('./../assets/images/location.png'),
  home: require('./../assets/images/home.png'),
  myCity: require('./../assets/images/cityscape.png'),
  mysetting: require('./../assets/images/setting.png'),
  umbrella: require('./../assets/images/umbrella.png'),
  partlyCloudy: require('./../assets/images/PartlyCloudy.png'),
  temperature: require('./../assets/images/medical.png'),
  rain: require('./../assets/images/rain.png'),
  snowfall: require('./../assets/images/snowfall.png'),
  sun: require('./../assets/images/sun.png'),
  sun256: require('./../assets/images/sun-256.png'),
  uv: require('./../assets/images/uv.png'),
  wind: require('./../assets/images/wind.png'),
  back: require('./../assets/images/back.png'),
  navigation_arrow: require('./../assets/images/navigation.png'),
  next: require('./../assets/images/next.png'),
  coludy: require('./../assets/images/cloudy.png'),
  coludy_256: require('./../assets/images/cloudy-256.png'),
};
